Online_Shopping_Cart_Dot_NET_CORE6/Models/Admin.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Admin
    {
        [Key]
        public int A_Id { get; set; }
        public string A_Email { get; set; }
        public string A_Password { get; set; }

    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Brand
    {
        [Key]
        public int Brnd_Id { get; set; }
        public string Brand_Name { get; set; }

    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Category
    {
        [Key]
        public int Cat_ID { get; set; }
        public string Cat_Name { get; set; }
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/ErrorViewModel.cs
namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/FeedBack.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class FeedBack
    {
        [Key]
        public int Fd_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/Invoice.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Invoice
    {
        [Key]
        public int InvoiceId { get; set; }
        public int OrderId { get; set; }
        public decimal TotalAmount { get; set; }
        public DateTime InvoiceDate { get; set; }

        public Orders Orders { get; set;}
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/Orders.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Orders
    {
        [Key]
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public DateTime OrderDate { get; set; }

        public UserTb UserTb { get; set; }
        public Product Product { get; set; }
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Product
    {
        [Key]
        public int ProId { get; set; }
        public string ProName { get; set; }
        public int BrandId { get; set; }
        public int CategoryId { get; set; }
        public decimal ProPrice { get; set; }

        public Brand Brand { get; set; }
        public Category Category { get; set; }  
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/Shippment.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class Shippment
    {
        [Key]
        public int ShipmentId { get; set; }
        public int OrderId { get; set; }
        public DateTime ShipmentDate { get; set; }
        public string ShipmentStatus { get; set; }
        public Orders Orders { get; set;}
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Models/UserTb.cs
using System.ComponentModel.DataAnnotations;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Models
{
    public class UserTb
    {
        [Key]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public List<Orders> Orders { get; set; }
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Controllers/BrandsController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Shopping_Cart_Dot_NET_CORE6.Infrasturecture;
using Online_Shopping_Cart_Dot_NET_CORE6.Models;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IBrandRepo repo;

        public BrandsController(IBrandRepo _repo)
        {
            repo = _repo;
        }
        public IActionResult Index()
        {
            var getbrand = repo.Getbrand();
            return View(getbrand);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Brand model)
        {
            var save = repo.Create(model);
            return View(save);
        }

        public IActionResult Delete(int id)
        {
            var remove = repo.Delete(id);
            return RedirectToAction("Index");
            return View(remove);
        }
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Shopping_Cart_Dot_NET_CORE6.Infrasturecture;
using Online_Shopping_Cart_Dot_NET_CORE6.Models;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepo repo;

        public CategoryController(ICategoryRepo _repo)
        {
            repo = _repo;
        }
        public IActionResult Index()
        {
            var getcat = repo.GetCategories();
            return View(getcat);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category model)
        {
            var save = repo.Create(model);
            return View(save);   
        }
        public IActionResult Delete(int id)
        {
            var remove = repo.Delete(id);
            return RedirectToAction("Index");
            return View(remove);
        }


    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Shopping_Cart_Dot_NET_CORE6.Models;
using System.Diagnostics;

namespace Online_Shopping_Cart_Dot_NET_CORE6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Form()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Online_Shopping_Cart_Dot_NET_CORE6/Views/Brands/Create.cshtml
@model Online_Shopping_Cart_Dot_NET_CORE6.Models.Brand

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="col-md-8">
    <div class="ibox">

        <div class="ibox-body">
            <h1>Add New Brand</h1>
            <form asp-controller="Brands" asp-action="Create" method="post">
                <div class="form-group">
                    <label>Brand</label>
                    <input class="form-control" asp-for="Brand_Name" type="text"
                           placeholder="Enter Brand">
                </div>


                <div class="form-group">
                    <button class="btn btn-success" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

Online_Shopping_Cart_Dot_NET_CORE6/Views/Brands/Index.cshtml
@model IEnumerable<Online_Shopping_Cart_Dot_NET_CORE6.Models.Brand>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="col-md-12">
    <div class="ibox">

        <div class="ibox-body">
            <h3>View Brand</h3>
            <table class="table table-striped table-bordered table-hover" id="example-table" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Brnd_Id)
                            </td>


                            <td>
                                @Html.DisplayFor(modelItem => item.Brand_Name)
                            </td>
                            <td>
                                <a asp-controller="Brands" asp-action="Edit" asp-route-id="@item.Brnd_Id" class="btn btn-success">Edit</a>
                                <a asp-controller="Brands" asp-action="Delete" asp-route-id="@item.Brnd_Id" class="btn btn-danger">Delete</a>

                            </td>

                        </tr>
                    }
                </tbody>



            </table>

        </div>
    </div>
</div>

Online_Shopping_Cart_Dot_NET_CORE6/Views/Category/Create.cshtml
@model Online_Shopping_Cart_Dot_NET_CORE6.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

  
        <div class="col-md-8">
            <div class="ibox">

                <div class="ibox-body">
                    <h1>Add New Category</h1>
                    <form asp-controller="Category" asp-action="Create" method="post">
                        <div class="form-group">
                            <label>Category</label>
                            <input class="form-control" asp-for="Cat_Name" type="text"
                                   placeholder="Enter Category">
                        </div>
                        
                        
                        <div class="form-group">
                            <button class="btn btn-success" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    

Online_Shopping_Cart_Dot_NET_CORE6/Views/Category/Index.cshtml
@model IEnumerable<Online_Shopping_Cart_Dot_NET_CORE6.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="col-md-12">
    <div class="ibox">

        <div class="ibox-body">
            <h3>View Category</h3>
<table class="table table-striped table-bordered table-hover" id="example-table" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Action</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Cat_ID)
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.Cat_Name)
                </td>
                <td>
                                <a asp-controller="Category" asp-action="Edit" asp-route-id="@item.Cat_ID" class="btn btn-success">Edit</a>
                                <a asp-controller="Category" asp-action="Delete" asp-route-id="@item.Cat_ID" class="btn btn-danger">Delete</a>

                </td>
                
            </tr>
        }
    </tbody>

   

</table>

</div>
</div>
</div>

Online_Shopping_Cart_Dot_NET_CORE6/Views/Home/Form.cshtml
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<div class="page-content fade-in-up">
    <div class="row">
        <div class="col-md-8">
            <div class="ibox">

                <div class="ibox-body">
                    <h1>Add New Category</h1>
                    <form>
                        <div class="form-group">
                            <label>Email</label>
                            <input class="form-control" type="text"
                                   placeholder="Email address">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input class="form-control" type="password"
                                   placeholder="Password">
                        </div>
                        <div class="form-group">
                            <label class="ui-checkbox">
                                <input type="checkbox">
                                <span class="input-span"></span>Remamber me
                            </label>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-default" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Online_Shopping_Cart_Dot_NET_CORE6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="col-lg-3 col-md-6">
    <div class="ibox bg-success color-white widget-stat">
        <div class="ibox-body">
            <h2 class="m-b-5 font-strong">201</h2>
            <div class="m-b-5">NEW ORDERS</div><i class="ti-shopping-cart widget-stat-icon"></i>
            <div><i class="fa fa-level-up m-r-5"></i><small>25% higher</small></div>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6">
    <div class="ibox bg-info color-white widget-stat">
        <div class="ibox-body">
            <h2 class="m-b-5 font-strong">1250</h2>
            <div class="m-b-5">UNIQUE VIEWS</div><i class="ti-bar-chart widget-stat-icon"></i>
            <div><i class="fa fa-level-up m-r-5"></i><small>17% higher</small></div>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6">
    <div class="ibox bg-warning color-white widget-stat">
        <div class="ibox-body">
            <h2 class="m-b-5 font-strong">$1570</h2>
            <div class="m-b-5">TOTAL INCOME</div><i class="fa fa-money widget-stat-icon"></i>
            <div><i class="fa fa-level-up m-r-5"></i><small>22% higher</small></div>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6">
    <div class="ibox bg-danger color-white widget-stat">
        <div class="ibox-body">
            <h2 class="m-b-5 font-strong">108</h2>
            <div class="m-b-5">NEW USERS</div><i class="ti-user widget-stat-icon"></i>
            <div><i class="fa fa-level-down m-r-5"></i><small>-12% Lower</small></div>
        </div>
    </div>
</div>

Online_Shopping_Cart_Dot_NET_CORE6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Shopping_Cart_Dot_NET_CORE6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Online_Shopping_Cart_Dot_NET_CORE6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_Shopping_Cart_Dot_NET_CORE6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Online_Shopping_Cart_Dot_NET_CORE6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>